name: Build Image

on:
  push:
    branches:
      - main
    paths:
      - "binder/**"
      - "install/**"
      - ".github/workflows/build-image.yml"
  pull_request:
    paths:
      - "binder/**"
      - "install/**"
      - ".github/workflows/build-image.yml"
  workflow_dispatch:

env:
  DOCKER_TAG: base

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout files in repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
      - name: Free Disk Space for Docker
        uses: endersonmenezes/free-disk-space@7901478139cff6e9d44df5972fd8ab8fcade4db1  #v3.3.2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true

      # Pull Requests:
      # Build only (no push to GHCR)
      - name: Build image for PR validation
        if: github.event_name == 'pull_request'
        uses: jupyterhub/repo2docker-action@master
        with:
          IMAGE_NAME: erad2026
          NO_PUSH: true
          PUBLIC_REGISTRY_CHECK: true
          APPENDIX_FILE: binder/appendix.txt
          REPO2DOCKER_EXTRA_ARGS: --Repo2Docker.base_image=docker.io/library/buildpack-deps:noble
          FORCE_REPO2DOCKER_VERSION: jupyter-repo2docker==2026.04.0

      # Pushes to main:
      # Build and push image to GHCR
      - name: Build and push image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: "openradar"
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          ADDITIONAL_TAG: ${{ env.DOCKER_TAG }}
          PUBLIC_REGISTRY_CHECK: true
          APPENDIX_FILE: "binder/appendix.txt"
          REPO2DOCKER_EXTRA_ARGS: --Repo2Docker.base_image=docker.io/library/buildpack-deps:noble
          FORCE_REPO2DOCKER_VERSION: jupyter-repo2docker==2026.04.0

      - name: list docker images
        run: |
          echo "=== IMAGES ==="
          docker image ls -a

          echo "=== IMAGE DIGESTS ==="
          docker image ls --digests
      
          echo "=== FULL INSPECTION ==="
          docker system df

      - name: Run tests inside PR-built image
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm \
          -v $PWD:/work -w /work \
          erad2026:latest \
          bash -lc "ls -lart && which conda && which python"

      - name: Run tests inside GHCR image (main)
        if: github.event_name == 'push'
        run: |
          docker run --rm \
            ghcr.io/openradar/erad2026:latest \
            bash -lc "ls -lart && which conda && which python"

  test-image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openradar/erad2026:latest
      options: --user root
      env:
        BASE_URL: /${{ github.event.repository.name }}
    needs: [build-container]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses:  actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
      - name: Build
        run: |
          ls -lart
          which conda
          which python