name: Build Book

on:
  push:
    branches:
      - main
    paths-ignore:
      - "binder/**"
      - "install/**"
      - ".github/workflows/build-image.yaml"
  pull_request:
    paths-ignore:
      - "binder/**"
      - "install/**"
      - ".github/workflows/build-image.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-book:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/openradar/erad2026:latest
      options: --user root
      env:
        NODE_OPTIONS: "--dns-result-order=ipv4first"
        BASE_URL: /${{ github.event.repository.name }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2

      - name: Enable Jupyter root mode workaround
        run: |
          mkdir -p .jupyter
          echo "c.ServerApp.allow_root = True" > .jupyter/jupyter_server_config.py
          echo "JUPYTER_CONFIG_DIR=$PWD/.jupyter" >> "$GITHUB_ENV"

      - name: Set BASE_URL
        run: |
          REPO="${{ github.event.repository.name }}"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BASE_URL=/$REPO/_preview/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "BASE_URL=/$REPO" >> $GITHUB_ENV
          fi

      - name: Debug environment
        run: |
          which python
          which jupyter
          python --version
          jupyter kernelspec list

      - name: Build Jupyter Book
        run: |
          # execute several notebooks prior myst build to create needed output 
          ERAD2026_PREFIX=Fgora ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/dem_beamblockage.md
          ERAD2026_PREFIX=jastrebac_250m ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/dem_beamblockage.md
          ERAD2026_PREFIX=jastrebac_500m ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/dem_beamblockage.md
          ERAD2026_PREFIX=Fgora ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/gridding_data.md
          ERAD2026_PREFIX=jastrebac_250m ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/gridding_data.md
          ERAD2026_PREFIX=jastrebac_500m ERAD2026_SWEEP=sweep_0 jupytext --to notebook --execute notebooks/workflow/gridding_data.md
          myst build --execute --ci --html --execute-parallel 1

      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip _build/html

      - name: Write deployment metadata
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.event.pull_request.number }}" > pr.txt
          else
            echo "main" > pr.txt
          fi

      - name: Upload zipped book artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          name: book-zip
          path: |
            ./book.zip
            ./pr.txt
